-- MySQL Script generated by MySQL Workbench
-- Mon Aug 17 17:10:48 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema alquiler_peliculas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema alquiler_peliculas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alquiler_peliculas` DEFAULT CHARACTER SET utf8 ;
USE `alquiler_peliculas` ;

-- -----------------------------------------------------
-- Table `alquiler_peliculas`.`banco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alquiler_peliculas`.`banco` ;

CREATE TABLE IF NOT EXISTS `alquiler_peliculas`.`banco` (
  `idBanco` INT(18) NOT NULL AUTO_INCREMENT,
  `nombreBanco` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`idBanco`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `alquiler_peliculas`.`socio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alquiler_peliculas`.`socio` ;

CREATE TABLE IF NOT EXISTS `alquiler_peliculas`.`socio` (
  `nroSocio` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `apellido` VARCHAR(100) NULL DEFAULT NULL,
  `domicilio` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` VARCHAR(100) NULL DEFAULT NULL,
  `mail` VARCHAR(100) NULL DEFAULT NULL,
  `banco` INT(10) NULL DEFAULT NULL,
  `nroTarjeta` INT(18) NULL DEFAULT NULL,
  `envioMail` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`nroSocio`),
  INDEX `nroTarjeta` (`nroTarjeta` ASC) VISIBLE,
  INDEX `Socio_fk_` (`banco` ASC) VISIBLE,
  CONSTRAINT `Socio_fk_`
    FOREIGN KEY (`banco`)
    REFERENCES `alquiler_peliculas`.`banco` (`idBanco`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `alquiler_peliculas`.`alquiler`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alquiler_peliculas`.`alquiler` ;

CREATE TABLE IF NOT EXISTS `alquiler_peliculas`.`alquiler` (
  `nroAlquiler` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaAlquiler` VARCHAR(20) NOT NULL,
  `importeAlquiler` FLOAT NULL DEFAULT NULL,
  `socio` INT(11) NOT NULL,
  PRIMARY KEY (`nroAlquiler`),
  INDEX `socio` (`socio` ASC) VISIBLE,
  CONSTRAINT `Alquiler_fk_`
    FOREIGN KEY (`socio`)
    REFERENCES `alquiler_peliculas`.`socio` (`nroSocio`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `alquiler_peliculas`.`genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alquiler_peliculas`.`genero` ;

CREATE TABLE IF NOT EXISTS `alquiler_peliculas`.`genero` (
  `idGenero` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`idGenero`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `alquiler_peliculas`.`pelicula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alquiler_peliculas`.`pelicula` ;

CREATE TABLE IF NOT EXISTS `alquiler_peliculas`.`pelicula` (
  `CodPelicula` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NULL DEFAULT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `duracion` INT(11) NULL DEFAULT NULL,
  `stock` INT(11) NULL DEFAULT NULL,
  `genero` INT(11) NOT NULL,
  PRIMARY KEY (`CodPelicula`),
  INDEX `genero` (`genero` ASC) VISIBLE,
  CONSTRAINT `Pelicula_fk`
    FOREIGN KEY (`genero`)
    REFERENCES `alquiler_peliculas`.`genero` (`idGenero`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `alquiler_peliculas`.`lineaalquiler`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alquiler_peliculas`.`lineaalquiler` ;

CREATE TABLE IF NOT EXISTS `alquiler_peliculas`.`lineaalquiler` (
  `fechaDevolucion` VARCHAR(20) NULL DEFAULT NULL,
  `diasAlquiler` INT(11) NULL DEFAULT NULL,
  `importeLineaAlquiler` FLOAT NULL DEFAULT NULL,
  `pelicula` INT(11) NOT NULL,
  `alquiler` INT(11) NOT NULL,
  INDEX `pelicula` (`pelicula` ASC) VISIBLE,
  INDEX `alquiler` (`alquiler` ASC) VISIBLE,
  CONSTRAINT `LineaAlquiler_fk`
    FOREIGN KEY (`pelicula`)
    REFERENCES `alquiler_peliculas`.`pelicula` (`CodPelicula`)
    ON UPDATE CASCADE,
  CONSTRAINT `LineaAlquiler_fk_2`
    FOREIGN KEY (`alquiler`)
    REFERENCES `alquiler_peliculas`.`alquiler` (`nroAlquiler`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `alquiler_peliculas`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alquiler_peliculas`.`usuario` ;

CREATE TABLE IF NOT EXISTS `alquiler_peliculas`.`usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `contrasena` VARCHAR(50) NULL DEFAULT NULL,
  `estado` VARCHAR(4) NULL DEFAULT '1',
  `nivelAcceso` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `idUsuario` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `Usuario_fk_`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `alquiler_peliculas`.`socio` (`nroSocio`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `alquiler_peliculas`.`videoclub`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alquiler_peliculas`.`videoclub` ;

CREATE TABLE IF NOT EXISTS `alquiler_peliculas`.`videoclub` (
  `importePorDia` FLOAT NULL DEFAULT NULL,
  `plazoMaxADevolver` INT(11) NULL DEFAULT NULL,
  `cantMaxPelPendientes` INT(11) NULL DEFAULT NULL,
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



INSERT INTO `banco` VALUES (1,'x');
INSERT INTO `banco` VALUES (2,'Macro');

INSERT INTO `socio` VALUES (1,'admin', 'admin', null, '1111','admin@gmail.com', 1, null, 1);
INSERT INTO `socio` VALUES (2, 'Jacinto','Gonzales','sarmiento 123','123654789123','JGonzalez@gmail.com', 1, null, 1);

INSERT INTO `usuario` VALUES (1,'admin@gmail.com','admin', 1, 'admin');
INSERT INTO `usuario` VALUES (2,'JGonzalez@gmail.com','JGonzalez123', 2, 'user');

